### ISSUE TITLE
1.2 Compatibility

### ISSUE THREAD

**Issue by karl-** [karl-/vuo-nodes#2]
Some nodes compile but crash under the 1.2 sdk - 
- `Make Bar Graph`

**Comment by smokris** [comment]
One change I know of offhand — the `VuoImage_makeFromBuffer()` semantics changed.  That function now takes ownership of the pixel buffer, and therefore `freeCallback` is now required (can't be NULL).

**Comment by karl-** [comment]
fba6acfc5b1a9a07a77ba4e2362d48c020ced1d2 fixes this issue.
