### ISSUE TITLE
Average List: calculation error?

### ISSUE THREAD

**Issue by Kurville** [karl-/vuo-nodes#3]
There seems to be a calculation error with the `Average List` node: to keep the numbers at the output within the same range as the numbers coming in, I have to use a `Scale List` using this formula **1/(x*x)** in a `Calculate` node, with **x** being the number of samples in the `Average List`.

**Comment by karl-** [comment]
That does look wrong. The documentation for that node is also lacking.

**Comment by Kurville** [comment]
Glad to know you'll take a look at it!
